[package]
name = "av1parser"
version = "0.2.1"
authors = ["yoh <kawasaki.liamg@gmail.com>"]
description = "AV1 Bitstream Parser"

[dependencies]
byteorder = "1.2"
clap = "2.32"
hex = "0.4"
hdr10plus = { version = "1.0", optional = true }

[features]
metadata_hdr10plus = ["hdr10plus"]